return {
  {
    "nvim-treesitter/nvim-treesitter",
    build = ":TSUpdate",
    lazy = vim.fn.argc(-1) == 0,
    opts_extend = { "ensure_installed" },
    opts = {
      highlight = { enable = true },
      indent = { enable = true },
      ensure_installed = {
        "bash",
        "c",
        "diff",
        "html",
        "javascript",
        "jsdoc",
        "json",
        "jsonc",
        "lua",
        "luadoc",
        "luap",
        "markdown",
	"markdown_inline",
        "printf",
        "python",
        "query",
        "regex",
        "toml",
        "tsx",
	"typescript",
        "vim",
	"vimdoc",
        "xml",
        "yaml",
      },
    },
  }
}
