$font = Monospace

general {
    hide_cursor = true
}

animations {
    enabled = true
    bezier = linear, 1, 1, 0, 0
    animation = fadeIn, 1, 5, linear
    animation = fadeOut, 1, 5, linear
    animation = inputFieldDots, 1, 2, linear
}

background {
    path = screenshot
    blur_passes = 4
}

# INPUT FIELD
input-field {
    size = 350, 50
    outline_thickness = 2

    outer_color = rgb(68, 68, 68)
    check_color = rgb(200, 200, 200)
    fail_color = rgb(136, 136, 136)
    capslock_color = rgb(255, 255, 255)

    inner_color = rgba(30, 30, 30, 0.7)
    font_color = rgb(200, 200, 200)

    fade_on_empty = false
    rounding = 5

    font_family = $font
    placeholder_text = <i>Input password...</i>
    fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>

    dots_size = 0.4
    dots_spacing = 0.3

    position = 0, -80
    halign = center
    valign = center
}

# TIME
label {
    text = $TIME
    font_size = 80
    font_family = $font
    color = rgb(200, 200, 200)

    position = 0, 150
    halign = center
    valign = center
}

# DATE
label {
    text = cmd[update:60000] date +"%A, %d %B"
    font_size = 20
    font_family = $font
    color = rgb(136, 136, 136)

    position = 0, 70
    halign = center
    valign = center
}

# KEYBOARD LAYOUT
label {
    text = $LAYOUT[pt,us]
    font_size = 18
    font_family = $font
    color = rgb(136, 136, 136)

    onclick = hyprctl switchxkblayout all next

    position = 230, -80
    halign = center
    valign = center
}
