{
  imports = [
    ./hyprland
    ./cliphist.nix
    ./fuzzel.nix
    ./gtk.nix
    ./hypridle.nix
    ./hyprlock.nix
    ./kanshi.nix
    ./qt.nix
    ./swappy.nix
    ./swaync.nix
    ./swayosd.nix
    ./waybar.nix
    ./wlogout.nix
    ./wlsunset.nix
    ./wpaperd.nix
  ];
}
